In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
np.random.seed(1)

In [4]:
X=2*np.random.rand(100,1)
y=4+3*X+1.5*X**2+np.random.randn(100,1)

In [5]:
X,y

(array([[8.34044009e-01],
        [1.44064899e+00],
        [2.28749635e-04],
        [6.04665145e-01],
        [2.93511782e-01],
        [1.84677190e-01],
        [3.72520423e-01],
        [6.91121454e-01],
        [7.93534948e-01],
        [1.07763347e+00],
        [8.38389029e-01],
        [1.37043900e+00],
        [4.08904499e-01],
        [1.75623487e+00],
        [5.47751864e-02],
        [1.34093502e+00],
        [8.34609605e-01],
        [1.11737966e+00],
        [2.80773877e-01],
        [3.96202978e-01],
        [1.60148914e+00],
        [1.93652315e+00],
        [6.26848356e-01],
        [1.38464523e+00],
        [1.75277830e+00],
        [1.78921333e+00],
        [1.70088423e-01],
        [7.81095665e-02],
        [3.39660839e-01],
        [1.75628501e+00],
        [1.96693668e-01],
        [8.42215250e-01],
        [1.91577906e+00],
        [1.06633057e+00],
        [1.38375423e+00],
        [6.31031262e-01],
        [1.37300186e+00],
        [1.66925134e+00],
        [3.6

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
X_train.shape,Y_train.shape

((80, 1), (80, 1))

In [9]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
degree=2
poly_feature=PolynomialFeatures(degree=2,include_bias=False)

In [11]:
x_poly_train=poly_feature.fit_transform(X_train)

In [12]:
x_poly_train

array([[1.06725090e-01, 1.13902449e-02],
       [1.32688300e+00, 1.76061848e+00],
       [1.70088423e-01, 2.89300716e-02],
       [5.60887984e-01, 3.14595331e-01],
       [1.17311008e+00, 1.37618726e+00],
       [1.34093502e+00, 1.79810673e+00],
       [1.97772218e+00, 3.91138501e+00],
       [1.80675904e+00, 3.26437823e+00],
       [1.07763347e+00, 1.16129389e+00],
       [2.78552695e-01, 7.75916036e-02],
       [1.37043900e+00, 1.87810305e+00],
       [5.87228297e-01, 3.44837073e-01],
       [1.79177244e+00, 3.21044846e+00],
       [3.39660839e-01, 1.15369486e-01],
       [1.15677923e+00, 1.33813818e+00],
       [1.84677190e-01, 3.41056643e-02],
       [1.32758929e+00, 1.76249332e+00],
       [1.07179281e+00, 1.14873983e+00],
       [6.31031262e-01, 3.98200454e-01],
       [8.34609605e-01, 6.96573192e-01],
       [2.60057144e-01, 6.76297183e-02],
       [1.38375423e+00, 1.91477576e+00],
       [6.91121454e-01, 4.77648864e-01],
       [4.74053960e-01, 2.24727157e-01],
       [7.810956

In [13]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [14]:
model.fit(x_poly_train,Y_train)

LinearRegression()

In [15]:
model.coef_

array([[2.33915935, 1.71782948]])

In [16]:
model.intercept_

array([4.49951103])

In [18]:
y_pred=model.predict(x_poly_train)