In [1]:
import numpy as np

In [6]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [11]:
#some other methods to create array
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
import random
np.random.random_sample((5,))

array([0.7689809 , 0.98832139, 0.98427088, 0.38636106, 0.83100518])

In [28]:
#RESHAPING ARRAY
arr1=np.random.randint(1,5,size=(3,4))
print(arr1)
arr1=arr1.reshape(2,6)
print("\n")
print(arr1)

[[1 1 2 3]
 [2 4 2 2]
 [1 4 3 1]]


[[1 1 2 3 2 4]
 [2 2 1 4 3 1]]


In [35]:
arr1=arr1.reshape(3,4)
arr1>2

array([[False, False, False,  True],
       [False,  True, False, False],
       [False,  True,  True, False]])

In [36]:
arr1[0]

array([1, 1, 2, 3], dtype=int32)

In [37]:
arr1[0][3]

np.int32(3)

In [38]:
arr1[0:2]

array([[1, 1, 2, 3],
       [2, 4, 2, 2]], dtype=int32)

In [39]:
arr1[0:2,0:2]

array([[1, 1],
       [2, 4]], dtype=int32)

In [51]:
a1=np.array([[1,2],
    [3,4]])
a2=np.array([[4,5],
    [5,6]])
print(a1+a2)

[[ 5  7]
 [ 8 10]]


In [52]:
print(a1-a2)

[[-3 -3]
 [-2 -2]]


In [53]:
print(a1*a2)

[[ 4 10]
 [15 24]]


In [54]:
print(a1/a2)

[[0.25       0.4       ]
 [0.6        0.66666667]]


In [55]:
print(a1@a2)

[[14 17]
 [32 39]]


In [56]:
a3=np.array([1,2,3,4])
print(a3+1)

[2 3 4 5]
