In [2]:
import numpy as np

In [4]:
np.__version__


'2.1.2'

In [6]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [7]:
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)

[1 2 3 4 5]


In [13]:
l=[1,2,3,4,5.5]
arr=np.array(l)
print(arr)
print(arr[3])

[1.  2.  3.  4.  5.5]
4.0


In [9]:
arr.ndim

1

In [10]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1.ndim)

2


In [12]:
#MATRIX
mat=np.matrix([[1,2,3],[4,5,4]])
property(type(mat))

In [17]:
#DEEP AND SHALLOW ARRAY
#SHALLOW-
shallow=np.array([1,2,3,4])
s=shallow
print(s)
shallow[0]=10
print(s)
print("---------------------------")
#DEEP-
deep=np.array([1,2,3,4])
d=deep.copy()
print(d)
deep[0]=10
print(d)

[1 2 3 4]
[10  2  3  4]
---------------------------
[1 2 3 4]
[1 2 3 4]


In [18]:
#MULTIPLE WAYS TO CREATE ARRAY
#BY fromfunction
ff=np.fromfunction(lambda i,j:i==j,(3,3))
print(ff)
print(ff.shape)


[[ True False False]
 [False  True False]
 [False False  True]]
(3, 3)


In [20]:
#from Iterable
iter=(i for i in range(0,5))
np.fromiter(iter,int)




array([0, 1, 2, 3, 4])

In [21]:
#other methods of numpy>> to generate sequnce of nos
np.arange(1, 10, 0.1) #Return evenly spaced values within a given interval.

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])