In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [3]:
arr=np.array([1,2,3,4])
np.expand_dims(arr,axis=0)

array([[1, 2, 3, 4]])

In [5]:
arr=np.array([[1,2,3],[4,5,6]])
np.expand_dims(arr,axis=1)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [6]:
np.squeeze(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.repeat(arr,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [8]:
np.roll(arr,-1)

array([[2, 3, 4],
       [5, 6, 1]])

In [9]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [10]:
np.cos(arr)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [11]:
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [13]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [14]:
np.min(arr)

np.int64(1)

In [15]:
np.max(arr)

np.int64(6)

In [19]:
ar=np.array([1,2,5,1,7,3])
np.sort(ar)

array([1, 1, 2, 3, 5, 7])

In [21]:
np.count_nonzero(ar)

6

In [22]:
np.extract(ar>3,ar)

array([5, 7])

In [23]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(arr)

np.float64(0.0)

In [25]:
# np.linalg.inv(arr)